questlist/questlist/questions/urls.py
from django.urls import path

from . import views

app_name='questions'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
]

questlist/questlist/questlist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('questions.urls', namespace='questions')),
    path('admin/', admin.site.urls),
]

questlist/questlist/questions/models.py
from django.db import models

class Question(models.Model):
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text

questlist/questlist/questions/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Question


def index(request):
    list = Question.objects.all()
    return render(request, 'questions/index.html', {'list': list})

def add(request):
    try:
        text = request.POST['text']
    except KeyError:
        return render(request, 'questions/index.html', {
            'error_message': "Поле текста пустое",
            'list': []
        })
    else:
        question = Question()
        question.text = text
        question.save()
        return HttpResponseRedirect(reverse('questions:index'))

questlist/questlist/questions/templates/questions/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вопросы</title>
</head>
<body>
<h1>Вопросы</h1>
{% if list %}
    <ul>
    {% for question in list %}
        <li>{{ question.text }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>Вопросов пока нет</p>
{% endif %}

<h1>Новый вопрос</h1>
<form action="{% url 'questions:add' %}" method="post">
{% csrf_token %}
    <input type="text" name="text" id="text">
    <label for="text">Текст вопроса</label><br>
<input type="submit" value="Добавить">
</form>

</body>
</html>